### ISSUE TITLE
Install results in " X App not installed"

### ISSUE THREAD

**Issue by jsavage** [ruuvi/Android_RuuvitagScanner#1]
I emailed the apk to my phone hoping that it would be an improvement over the original Centra app which I had previously uninstalled. I  downloaded the apk and started to install it. I accepted the security warning and ticked unknown sources  but still no dice.  Error message X  App not installed
This is on a Samsung SM-G360F running Android 5.0.2 security patch level 2017-04-01

**Comment by jsavage** [comment]
On a different Samsung phone (SM-G357F) running Android 4.4.4 I had the same result to the above report but below the error report there was a message about the fact that an app of the same name already exists (Centria one presumably) which has a conflicting certificate.  I  uninstalled the Centria app and now it just says X app not installed. 

Can anyone clarify the difference between this App and the Centria one and suggest how to get the app installed on this device.

**Comment by jsavage** [comment]
I have also tried downloading the Apk onto a Samsung S6 I have just purchased. This issues a message "There was a problem while parsing the package"

**Comment by jariisohanni** [comment]
Have you tried with the latest APK?

**Comment by jsavage** [comment]
mmm, I have just tried this on my S6 tonight.  I received a message "There was a problem while parsing the package."
